<a href="https://colab.research.google.com/github/aditya-singh-231/pytorch-campusx/blob/main/pytorch_training_pipeline_improved_L5_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [86]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [87]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [88]:
df.shape

(569, 33)

In [89]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [90]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### train test split

In [91]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [92]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [93]:
X_train

array([[-0.8578572 , -0.50506743, -0.84056642, ..., -0.30240836,
        -0.20350488,  1.7724167 ],
       [-0.04710088,  0.0741325 , -0.04160904, ...,  1.01054687,
         0.42560817,  1.15627063],
       [ 0.83029295, -0.67187701,  0.95879658, ...,  2.09467962,
         1.82416274,  1.17808111],
       ...,
       [ 1.45779613, -0.25948666,  1.40913994, ...,  1.64783099,
         1.07364191, -0.3502883 ],
       [ 1.87983367,  1.34142195,  2.04444576, ...,  2.08268369,
         0.03142706,  0.78712825],
       [-1.41816756, -0.09267708, -1.2901056 , ..., -0.0121067 ,
         0.3562323 ,  1.15627063]])

In [94]:
y_train

507    B
435    M
25     M
62     M
393    M
      ..
500    B
103    B
282    M
563    M
318    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [95]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [96]:
y_train

array([0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0])

### Numpy arrays to PyTorch tensors

In [97]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [98]:
X_train_tensor.shape

torch.Size([455, 30])

In [99]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [100]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()


  def forward(self, features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out

    """


  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

    """

### Important Parameters

In [101]:
learning_rate = 0.1
epochs = 25

In [102]:
# here we will use the inbuilt loss fn
loss_function=nn.BCELoss()

In [103]:
type(loss_function)

torch.nn.modules.loss.BCELoss

### Training Pipeline

In [104]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

#using built_in optimizers
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)   #model.parameters() will provide all the weights and biases

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate

  """   loss = model.loss_function(y_pred, y_train_tensor)   """
  loss=loss_function(y_pred, y_train_tensor.reshape(-1,1))
  #y_pred and y_train_tensor should be of same shape

  #clear gradients i.e. make them equal to zero so that they should not accumulate
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  #update parameters
  optimizer.step()


  """

  # parameters update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  """


  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.901723325252533
Epoch: 2, Loss: 0.6302874684333801
Epoch: 3, Loss: 0.4938993752002716
Epoch: 4, Loss: 0.417948842048645
Epoch: 5, Loss: 0.3688618838787079
Epoch: 6, Loss: 0.333983838558197
Epoch: 7, Loss: 0.3076285123825073
Epoch: 8, Loss: 0.2868387997150421
Epoch: 9, Loss: 0.2699112892150879
Epoch: 10, Loss: 0.25578945875167847
Epoch: 11, Loss: 0.24378013610839844
Epoch: 12, Loss: 0.23340781033039093
Epoch: 13, Loss: 0.2243345081806183
Epoch: 14, Loss: 0.21631258726119995
Epoch: 15, Loss: 0.2091560661792755
Epoch: 16, Loss: 0.20272211730480194
Epoch: 17, Loss: 0.19689907133579254
Epoch: 18, Loss: 0.19159813225269318
Epoch: 19, Loss: 0.18674761056900024
Epoch: 20, Loss: 0.1822890192270279
Epoch: 21, Loss: 0.1781739443540573
Epoch: 22, Loss: 0.17436200380325317
Epoch: 23, Loss: 0.17081908881664276
Epoch: 24, Loss: 0.16751624643802643
Epoch: 25, Loss: 0.1644286811351776

In [105]:
model.linear.bias

Parameter containing:
tensor([-0.0777], requires_grad=True)

In [106]:
model.linear.weight

Parameter containing:
tensor([[ 0.1663,  0.2268,  0.3147,  0.1073,  0.1416,  0.2186,  0.2563,  0.3657,
          0.0240, -0.1394,  0.1090,  0.0218,  0.2512,  0.1428,  0.0528, -0.1255,
          0.0407,  0.0333, -0.1199, -0.1193,  0.2071,  0.2728,  0.3637,  0.1564,
          0.0572,  0.0427,  0.1804,  0.4225,  0.1191,  0.2065]],
       requires_grad=True)

### Evaluation

In [108]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5754078030586243